apply plugin: 'com.android.library'

android {
    namespace "com.mikey.auth"
    compileSdkVersion 35
    defaultConfig {
        minSdkVersion 25
        targetSdkVersion 35
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.credentials:credentials:1.3.0'
    implementation 'androidx.credentials:credentials-play-services-auth:1.3.0'
    implementation 'com.google.android.libraries.identity.googleid:googleid:1.1.1'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
}
