using UnityEditor;
using UnityEngine;

namespace Mikey.FightEditor
{
    /// <summary>One-shot setup for the kimono fighter: import settings and materials.
    ///
    /// This exists as a script rather than as inspector clicks because the settings have to be
    /// reproducible — the fighter's FBX is regenerated by a Blender script whenever the body or
    /// the garment changes, and a regenerated asset comes back as Generic with no materials.
    /// Re-running this method restores the whole setup.
    /// </summary>
    public static class FighterImportSetup
    {
        const string CharacterDir = "Assets/Fight/character";
        const string ModelPath = CharacterDir + "/KimonoFighter.fbx";
        const string ShaderPath = CharacterDir + "/Character.shader";
        const string NormalPath = CharacterDir + "/kimono/T_Kimono_Normal.png";
        const string AoPath = CharacterDir + "/kimono/T_Kimono_AO.png";

        [MenuItem("Mikey/Setup Kimono Fighter")]
        public static void Run()
        {
            SetUpModel();
            SetUpNormalMap();
            CreateMaterials();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("FighterImportSetup: done");
        }

        static void SetUpModel()
        {
            var importer = AssetImporter.GetAtPath(ModelPath) as ModelImporter;
            if (importer == null)
                throw new System.IO.FileNotFoundException(ModelPath + " is not in the project");

            importer.animationType = ModelImporterAnimationType.Human;
            importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
            importer.importAnimation = false;   // clips come from the mocap files, not from here
            importer.SaveAndReimport();
        }

        /// <summary>Without this the relief reads as coloured noise rather than folds.</summary>
        static void SetUpNormalMap()
        {
            var importer = AssetImporter.GetAtPath(NormalPath) as TextureImporter;
            if (importer == null)
                throw new System.IO.FileNotFoundException(NormalPath + " is not in the project");
            if (importer.textureType == TextureImporterType.NormalMap)
                return;

            importer.textureType = TextureImporterType.NormalMap;
            importer.SaveAndReimport();
        }

        static void CreateMaterials()
        {
            var shader = AssetDatabase.LoadAssetAtPath<Shader>(ShaderPath);
            if (shader == null)
                throw new System.IO.FileNotFoundException(ShaderPath + " is not in the project");

            var normal = AssetDatabase.LoadAssetAtPath<Texture>(NormalPath);
            var ao = AssetDatabase.LoadAssetAtPath<Texture>(AoPath);
            if (ao == null)
                throw new System.IO.FileNotFoundException(AoPath + " is not in the project");

            // Skin is shared: player and enemy are the same body and differ only in cloth.
            var skin = Material(shader, CharacterDir + "/M_Fighter_Skin.mat");
            skin.SetColor("_BaseColor", new Color(0.78f, 0.60f, 0.48f));
            skin.SetFloat("_AlbedoGamma", 1f);
            skin.SetFloat("_Smoothness", 0.22f);

            Kimono(shader, CharacterDir + "/M_Player_Kimono.mat", normal, ao,
                   new Color(0.91f, 0.89f, 0.85f), new Color(0.23f, 0.29f, 0.62f));
            Kimono(shader, CharacterDir + "/M_Enemy_Kimono.mat", normal, ao,
                   new Color(0.16f, 0.16f, 0.19f), new Color(0.48f, 0.12f, 0.16f));
        }

        /// <summary>The kimono has no albedo texture — all five of its source materials are flat
        /// colours — so the baked AO serves as the base map and the tint supplies the colour.
        /// _AlbedoGamma is forced to 1: its 0.45 default exists to lift the near-black diffuse of
        /// the previous character and would wash an AO map out.
        ///
        /// The belt is a separate submesh in the source garment, but the export merges the cloth
        /// into one mesh, so the belt colour is carried as the rim rather than as a second
        /// material — one draw call instead of two on a mobile target.
        /// </summary>
        static void Kimono(Shader shader, string path, Texture normal, Texture ao,
                           Color cloth, Color accent)
        {
            var mat = Material(shader, path);
            mat.SetTexture("_BaseMap", ao);
            mat.SetTexture("_BumpMap", normal);
            mat.SetColor("_BaseColor", cloth);
            mat.SetColor("_RimColor", accent);
            mat.SetFloat("_AlbedoGamma", 1f);
            mat.SetFloat("_BumpScale", 1.4f);
            mat.SetFloat("_Smoothness", 0.12f);   // cotton, not silk
        }

        static Material Material(Shader shader, string path)
        {
            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;
            return mat;
        }
    }
}
