using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace Mikey.FightEditor
{
    /// <summary>One-shot setup for both kimono fighters: import settings and materials.
    ///
    /// This exists as a script rather than as inspector clicks because the settings have to be
    /// reproducible — the fighters' FBX files are regenerated by a Blender script whenever a body
    /// or the garment changes, and a regenerated asset comes back as Generic with no materials.
    /// Re-running this method restores the whole setup.
    /// </summary>
    public static class FighterImportSetup
    {
        const string CharacterDir = "Assets/Fight/character";
        // Оба бойца носят костюм, сшитый по поверхности тела (tools/Blender/export_sewn.py):
        // у подогнанного халата между тканью и телом 94 мм, и предплечье в этот зазор
        // проваливается. У сшитого по телу зазора нет по построению.
        const string PlayerModelPath = CharacterDir + "/KimonoFighterSewn.fbx";
        const string EnemyModelPath = CharacterDir + "/KimonoFighterSewn.fbx";
        const string ShaderPath = CharacterDir + "/Character.shader";
        const string NormalPath = CharacterDir + "/kimono/T_Kimono_Normal.png";
        const string AoPath = CharacterDir + "/kimono/T_Kimono_AO.png";

        const string BodyDir = CharacterDir + "/body";

        /// <summary>Every normal map the fighters sample, kimono and bodies alike. The body maps
        /// arrive with the model as plain PNGs and Unity types them Default, exactly as it did
        /// with the kimono map before this script existed.
        ///
        /// The named entries are the floor of the guarantee; the body folder is swept on top of
        /// them, so a third fighter's map is fixed the day it lands instead of importing as a
        /// colour texture forever. A list alone is the shape of defect this project has already
        /// shipped twice: the guard existed, but it was pinned to yesterday's asset paths.
        /// (The paired test keeps its own explicit list on purpose — a sweep of an empty folder
        /// passes without asserting anything.)</summary>
        static string[] NormalMapPaths()
        {
            var named = new[]
            {
                NormalPath,
                BodyDir + "/Ch28_1001_Normal.png",   // Ch28_body, Ch28_hair
                BodyDir + "/Remy_Body_Normal.png",   // Bodymat, Eyelashmat
                BodyDir + "/Remy_Hair_Normal.png",   // Hairmat
            };
            if (!Directory.Exists(BodyDir))
                return named;   // let the named paths report the miss with a usable message
            return named
                .Concat(Directory.GetFiles(BodyDir, "*Normal*.png")
                    .Select(p => p.Replace('\\', '/')))
                .Distinct()
                .ToArray();
        }

        [MenuItem("Mikey/Setup Kimono Fighters")]
        public static void Run()
        {
            SetUpModel(PlayerModelPath);
            SetUpModel(EnemyModelPath);
            SetUpNormalMaps();
            SetUpAoMap();
            CreateMaterials();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("FighterImportSetup: done");
        }

        static void SetUpModel(string modelPath)
        {
            var importer = AssetImporter.GetAtPath(modelPath) as ModelImporter;
            if (importer == null)
                throw new System.IO.FileNotFoundException(modelPath + " is not in the project");

            importer.animationType = ModelImporterAnimationType.Human;
            importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
            importer.importAnimation = false;   // clips come from the mocap files, not from here
            // KimonoCloth reads the garment's vertices to find the belt and to decide which of
            // them the solver may move. Without a CPU copy that array comes back empty and the
            // cloth silently pins itself shut. Cheap here — the kimono is 4797 vertices.
            importer.isReadable = true;
            importer.SaveAndReimport();
            // Nothing here for the body's own maps: the export writes them as files next to the
            // model (body/<name>.png) and Unity resolves them on a plain import. They were briefly
            // embedded in the FBX instead, which needs ModelImporter.ExtractTextures — see
            // Models_BodyMeshCarriesItsDiffuse for what a body without them looks like.
        }

        /// <summary>Without this the relief reads as coloured noise rather than folds: a map left
        /// as a colour texture is gamma-decoded, which skews X and Y around 0.5 and gives relief
        /// of the wrong magnitude everywhere it is sampled.</summary>
        static void SetUpNormalMaps()
        {
            foreach (var path in NormalMapPaths())
            {
                var importer = AssetImporter.GetAtPath(path) as TextureImporter;
                if (importer == null)
                    throw new System.IO.FileNotFoundException(path + " is not in the project");
                if (importer.textureType == TextureImporterType.NormalMap)
                    continue;

                importer.textureType = TextureImporterType.NormalMap;
                importer.SaveAndReimport();
            }
        }

        /// <summary>bake() writes this map with is_data=True — linear values, not sRGB. Unity
        /// defaults a new PNG's import to sRGB, which decodes it a second time and crushes the
        /// midtones before _AlbedoGamma even gets a chance to apply.</summary>
        static void SetUpAoMap()
        {
            var importer = AssetImporter.GetAtPath(AoPath) as TextureImporter;
            if (importer == null)
                throw new System.IO.FileNotFoundException(AoPath + " is not in the project");
            if (!importer.sRGBTexture)
                return;

            importer.sRGBTexture = false;
            importer.SaveAndReimport();
        }

        /// <summary>FightSandbox's key light, colour times intensity, as URP hands it to the
        /// shader: a warm directional at intensity 11, so (1, 0.78, 0.5) * 11.
        ///
        /// Read from the scene rather than guessed — `Key Sun` in FightSandbox.unity. If that
        /// light is retuned, these numbers go stale and every fighter tint drifts with it.
        /// The alternative, sampling the light at import time, would tie asset import to
        /// whichever scene happened to be open, which is worse.</summary>
        static readonly Color KeySun = new Color(11.0f, 8.58f, 5.50f);

        /// <summary>What the base map contributes to albedo on a typical texel, after
        /// _AlbedoGamma. The map is the baked AO and raw AO is very dark here — median 0.063
        /// over the atlas — because the garment is layered and everything between jacket,
        /// shirt and pants bakes near black. Under gamma 0.2 that floor lifts to 0.063^0.2 ≈
        /// 0.58, so the map shades the cloth instead of staining it.
        ///
        /// This is what the camouflage blotching was: an occlusion map doing an albedo's job
        /// at full contrast. The kimono has no albedo texture at all, so AO is the only map
        /// there is — the fix is not to remove it but to flatten its range until it reads as
        /// soft shading in folds.</summary>
        const float AoTypical = 0.60f;

        /// <summary>Takes the colour we want ON SCREEN and returns the tint that produces it,
        /// dividing out both things that sit between a tint and a pixel: the key light and the
        /// base map. Miss the light and a "black" 0.07 renders tan-gold; miss the map and the
        /// coloured belts render black. Both mistakes were shipped before this existed.</summary>
        static Color Lit(float r, float g, float b)
        {
            return new Color(r / (KeySun.r * AoTypical),
                             g / (KeySun.g * AoTypical),
                             b / (KeySun.b * AoTypical));
        }

        static void CreateMaterials()
        {
            var shader = AssetDatabase.LoadAssetAtPath<Shader>(ShaderPath);
            if (shader == null)
                throw new System.IO.FileNotFoundException(ShaderPath + " is not in the project");

            var normal = AssetDatabase.LoadAssetAtPath<Texture>(NormalPath);
            var ao = AssetDatabase.LoadAssetAtPath<Texture>(AoPath);
            if (ao == null)
                throw new System.IO.FileNotFoundException(AoPath + " is not in the project");

            // No skin material: the bodies arrive from Mixamo with their own materials and face
            // textures, and painting a flat colour over them would undo exactly that.
            //
            // Both cloths are black, and the accents are blue for the player, RED for the
            // enemy — the colours originally specified. (A round of these was briefly two
            // blues, which lost the red; reverted.)
            //
            // The tints go through Lit() rather than being written literally. Character.shader
            // computes `albedo * mainLight.color`, and in URP mainLight.color already carries
            // the light's intensity — so a tint is not what lands on screen. A plain 0.07
            // "near-black" rendered as 0.07 * 11 = 0.77 red: the tan-gold, blotchy, glowing
            // garment the owner kept reporting. The accent at 0.48 went to 5.3 and blew out
            // to white-hot. Both were me picking colours as if the light were 1.0.
            Kimono(shader, CharacterDir + "/M_Player_Kimono.mat", normal, ao,
                   Lit(0.13f, 0.115f, 0.12f), Lit(0.10f, 0.17f, 0.55f));
            Kimono(shader, CharacterDir + "/M_Enemy_Kimono.mat", normal, ao,
                   Lit(0.13f, 0.115f, 0.12f), Lit(0.52f, 0.09f, 0.11f));

            // Belt is its own submesh again (kimono_fit.py: capture_belt_mask /
            // apply_belt_split), so it gets its own material rather than borrowing the rim.
            Belt(shader, CharacterDir + "/M_Player_Belt.mat", normal, ao,
                 Lit(0.10f, 0.17f, 0.55f));
            Belt(shader, CharacterDir + "/M_Enemy_Belt.mat", normal, ao,
                 Lit(0.52f, 0.09f, 0.11f));
        }

        /// <summary>The kimono has no albedo texture — all five of its source materials are flat
        /// colours — so the baked AO serves as the base map and the tint supplies the colour.
        /// _AlbedoGamma is forced to 1: its 0.45 default exists to lift the near-black diffuse of
        /// the previous character and would wash an AO map out.
        ///
        /// _RimColor is a fresnel highlight over the whole silhouette (see Character.shader),
        /// tinted per team so the two fighters read apart even in the mist background — it is
        /// not, and cannot be, the belt colour. The belt itself is Belt(), below.
        /// </summary>
        static void Kimono(Shader shader, string path, Texture normal, Texture ao,
                           Color cloth, Color accent)
        {
            var mat = ClothLike(shader, path, normal, ao, cloth);
            mat.SetColor("_RimColor", accent);
        }

        /// <summary>Kimono_low carries two submeshes on export — cloth and belt — sharing the
        /// same baked atlas, so the belt gets real AO/normal detail rather than a flat patch;
        /// _BaseColor is what makes player and enemy belts different colours as the spec asks
        /// for.
        ///
        /// _RimColor has to be set here too, not left to the shader default: the rim is one
        /// fresnel edge around the whole fighter, so it cannot change hue where the belt starts.
        /// The default (0.85, 0.92, 1) at _RimStrength 1.4 would ring the belt in cold white
        /// while the cloth around it is rimmed in the team colour. It is set to the belt's own
        /// colour because that colour IS the team accent Kimono() passes as its rim —
        /// CreateMaterials() passes the same value to both — so the edge stays one hue.
        /// </summary>
        static void Belt(Shader shader, string path, Texture normal, Texture ao, Color color)
        {
            var mat = ClothLike(shader, path, normal, ao, color);
            mat.SetColor("_RimColor", color);
        }

        static Material ClothLike(Shader shader, string path, Texture normal, Texture ao,
                                  Color baseColor)
        {
            var mat = Material(shader, path);
            mat.SetTexture("_BaseMap", ao);
            mat.SetTexture("_BumpMap", normal);
            mat.SetColor("_BaseColor", baseColor);
            // Gamma 0.2, the shader's floor, not the 1 that was forced here before. An
            // earlier note claimed 0.45 "would wash an AO map out"; it has that backwards.
            // Raw AO runs median 0.063 with a long bright tail, so at gamma 1 the tint is
            // multiplied by anything from 0.06 to 1.0 across the garment — that spread IS
            // the blotching, and it is also what swallowed the coloured belts. 0.2 pulls the
            // range to roughly 0.58..1.0: folds still read, stains do not.
            mat.SetFloat("_AlbedoGamma", 0.2f);
            // Character.shader ADDS the rim: color += _RimColor * rim * _RimStrength. Its 1.4
            // default was tuned against a pale cloth, where the added light barely registers.
            // On black cloth the same rim is the brightest thing on the fighter and reads as
            // the garment glowing — which is exactly what it looked like. Halved rather than
            // removed: the rim is what separates a dark fighter from the misty background.
            mat.SetFloat("_RimStrength", 0.7f);
            // THE camouflage. The baked normal map is not usable at full strength: its blue
            // channel averages 0.641 with sigma 0.377, where a sound tangent-space map sits
            // near 1.0 almost everywhere. Normals that far off vertical are not folds, they
            // are noise — the bake has 12k target triangles and only 5% UV coverage, so a
            // texel spans far too much surface to hold a fold. At _BumpScale 1.4 that noise
            // drove the diffuse term and painted the garment in dark camouflage blotches.
            //
            // Verified by substitution, not by argument: rendered at 0 the cloth came out
            // clean and even, at 1.4 blotched. 0.3 keeps a trace of relief without the noise
            // taking over. The real repair is the bake — see the UV coverage note — and when
            // that lands this can go back up.
            mat.SetFloat("_BumpScale", 0.3f);
            mat.SetFloat("_Smoothness", 0.12f);   // cotton, not silk

            // THE glow. Character.shader computes specular as mainLight.color * _SpecStrength
            // * _Smoothness, and mainLight.color carries the light's intensity — so the 0.5
            // default peaked at 11 * 0.5 * 0.12 = 0.66 warm, five times the cloth's own 0.13,
            // smeared over the whole garment because _Smoothness 0.12 makes specPower only
            // 2^2.2 ≈ 4.6, a lobe wide enough to catch almost every surface facing the sun.
            // That is the gold-orange sheen that kept coming back after each tint fix: it was
            // never the tint and never the rim, it was the highlight.
            //
            // Set so the peak lands near 0.08 — cotton keeps a soft sheen instead of reading
            // as a flat void, but the cloth's own colour stays the brightest thing on it.
            mat.SetFloat("_SpecStrength", 0.08f / (KeySun.r * 0.12f));
            return mat;
        }

        static Material Material(Shader shader, string path)
        {
            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;
            return mat;
        }
    }
}
