using UnityEditor;
using UnityEngine;

namespace Mikey.FightEditor
{
    /// <summary>One-shot setup for both kimono fighters: import settings and materials.
    ///
    /// This exists as a script rather than as inspector clicks because the settings have to be
    /// reproducible — the fighters' FBX files are regenerated by a Blender script whenever a body
    /// or the garment changes, and a regenerated asset comes back as Generic with no materials.
    /// Re-running this method restores the whole setup.
    /// </summary>
    public static class FighterImportSetup
    {
        const string CharacterDir = "Assets/Fight/character";
        const string PlayerModelPath = CharacterDir + "/KimonoFighter_Player.fbx";
        const string EnemyModelPath = CharacterDir + "/KimonoFighter_Enemy.fbx";
        const string ShaderPath = CharacterDir + "/Character.shader";
        const string NormalPath = CharacterDir + "/kimono/T_Kimono_Normal.png";
        const string AoPath = CharacterDir + "/kimono/T_Kimono_AO.png";

        /// <summary>Every normal map the fighters sample, kimono and bodies alike. The body maps
        /// arrive with the model as plain PNGs and Unity types them Default, exactly as it did
        /// with the kimono map before this script existed.</summary>
        static readonly string[] NormalMapPaths =
        {
            NormalPath,
            CharacterDir + "/body/Ch28_1001_Normal.png",   // Ch28_body, Ch28_hair
            CharacterDir + "/body/Remy_Body_Normal.png",   // Bodymat, Eyelashmat
            CharacterDir + "/body/Remy_Hair_Normal.png",   // Hairmat
        };

        [MenuItem("Mikey/Setup Kimono Fighter")]
        public static void Run()
        {
            SetUpModel(PlayerModelPath);
            SetUpModel(EnemyModelPath);
            SetUpNormalMaps();
            SetUpAoMap();
            CreateMaterials();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("FighterImportSetup: done");
        }

        static void SetUpModel(string modelPath)
        {
            var importer = AssetImporter.GetAtPath(modelPath) as ModelImporter;
            if (importer == null)
                throw new System.IO.FileNotFoundException(modelPath + " is not in the project");

            importer.animationType = ModelImporterAnimationType.Human;
            importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
            importer.importAnimation = false;   // clips come from the mocap files, not from here
            importer.SaveAndReimport();
            // Nothing here for the body's own maps: the export writes them as files next to the
            // model (body/<name>.png) and Unity resolves them on a plain import. They were briefly
            // embedded in the FBX instead, which needs ModelImporter.ExtractTextures — see
            // Models_BodyMeshCarriesItsDiffuse for what a body without them looks like.
        }

        /// <summary>Without this the relief reads as coloured noise rather than folds: a map left
        /// as a colour texture is gamma-decoded, which skews X and Y around 0.5 and gives relief
        /// of the wrong magnitude everywhere it is sampled.</summary>
        static void SetUpNormalMaps()
        {
            foreach (var path in NormalMapPaths)
            {
                var importer = AssetImporter.GetAtPath(path) as TextureImporter;
                if (importer == null)
                    throw new System.IO.FileNotFoundException(path + " is not in the project");
                if (importer.textureType == TextureImporterType.NormalMap)
                    continue;

                importer.textureType = TextureImporterType.NormalMap;
                importer.SaveAndReimport();
            }
        }

        /// <summary>bake() writes this map with is_data=True — linear values, not sRGB. Unity
        /// defaults a new PNG's import to sRGB, which decodes it a second time and crushes the
        /// midtones before _AlbedoGamma even gets a chance to apply.</summary>
        static void SetUpAoMap()
        {
            var importer = AssetImporter.GetAtPath(AoPath) as TextureImporter;
            if (importer == null)
                throw new System.IO.FileNotFoundException(AoPath + " is not in the project");
            if (!importer.sRGBTexture)
                return;

            importer.sRGBTexture = false;
            importer.SaveAndReimport();
        }

        static void CreateMaterials()
        {
            var shader = AssetDatabase.LoadAssetAtPath<Shader>(ShaderPath);
            if (shader == null)
                throw new System.IO.FileNotFoundException(ShaderPath + " is not in the project");

            var normal = AssetDatabase.LoadAssetAtPath<Texture>(NormalPath);
            var ao = AssetDatabase.LoadAssetAtPath<Texture>(AoPath);
            if (ao == null)
                throw new System.IO.FileNotFoundException(AoPath + " is not in the project");

            // No skin material: the bodies arrive from Mixamo with their own materials and face
            // textures, and painting a flat colour over them would undo exactly that.
            Kimono(shader, CharacterDir + "/M_Player_Kimono.mat", normal, ao,
                   new Color(0.91f, 0.89f, 0.85f), new Color(0.23f, 0.29f, 0.62f));
            Kimono(shader, CharacterDir + "/M_Enemy_Kimono.mat", normal, ao,
                   new Color(0.16f, 0.16f, 0.19f), new Color(0.48f, 0.12f, 0.16f));

            // Belt is its own submesh again (kimono_fit.py: capture_belt_mask /
            // apply_belt_split), so it gets its own material rather than borrowing the rim.
            Belt(shader, CharacterDir + "/M_Player_Belt.mat", normal, ao,
                 new Color(0.23f, 0.29f, 0.62f));
            Belt(shader, CharacterDir + "/M_Enemy_Belt.mat", normal, ao,
                 new Color(0.48f, 0.12f, 0.16f));
        }

        /// <summary>The kimono has no albedo texture — all five of its source materials are flat
        /// colours — so the baked AO serves as the base map and the tint supplies the colour.
        /// _AlbedoGamma is forced to 1: its 0.45 default exists to lift the near-black diffuse of
        /// the previous character and would wash an AO map out.
        ///
        /// _RimColor is a fresnel highlight over the whole silhouette (see Character.shader),
        /// tinted per team so the two fighters read apart even in the mist background — it is
        /// not, and cannot be, the belt colour. The belt itself is Belt(), below.
        /// </summary>
        static void Kimono(Shader shader, string path, Texture normal, Texture ao,
                           Color cloth, Color accent)
        {
            var mat = ClothLike(shader, path, normal, ao, cloth);
            mat.SetColor("_RimColor", accent);
        }

        /// <summary>Kimono_low carries two submeshes on export — cloth and belt — sharing the
        /// same baked atlas, so the belt gets real AO/normal detail rather than a flat patch;
        /// _BaseColor is what makes player and enemy belts different colours as the spec asks
        /// for.
        ///
        /// _RimColor has to be set here too, not left to the shader default: the rim is one
        /// fresnel edge around the whole fighter, so it cannot change hue where the belt starts.
        /// The default (0.85, 0.92, 1) at _RimStrength 1.4 would ring the belt in cold white
        /// while the cloth around it is rimmed in the team colour. It is set to the belt's own
        /// colour because that colour IS the team accent Kimono() passes as its rim —
        /// CreateMaterials() passes the same value to both — so the edge stays one hue.
        /// </summary>
        static void Belt(Shader shader, string path, Texture normal, Texture ao, Color color)
        {
            var mat = ClothLike(shader, path, normal, ao, color);
            mat.SetColor("_RimColor", color);
        }

        static Material ClothLike(Shader shader, string path, Texture normal, Texture ao,
                                  Color baseColor)
        {
            var mat = Material(shader, path);
            mat.SetTexture("_BaseMap", ao);
            mat.SetTexture("_BumpMap", normal);
            mat.SetColor("_BaseColor", baseColor);
            mat.SetFloat("_AlbedoGamma", 1f);
            mat.SetFloat("_BumpScale", 1.4f);
            mat.SetFloat("_Smoothness", 0.12f);   // cotton, not silk
            return mat;
        }

        static Material Material(Shader shader, string path)
        {
            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;
            return mat;
        }
    }
}
